version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/monacoeditor/src/main/js"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/core/src/main/resources/META-INF/resources/primefaces-extensions/monacoeditor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/monacoeditor"
    schedule:
      interval: "weekly"
