name: Bug report
description: Create a report to help us improve
title: "Component: Title"
labels: "defect"
assignees: "melloware"
body:
  - type: markdown
    attributes:
      # yamllint disable rule:line-length
      value: "
        Thanks for taking the time to fill out this bug report!
      "
      # yamllint enable rule:line-length
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: Reproducer
      description: >
        Clone repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem,
        you'll have better chance to receive an answer and a solution and attach the GitHub Link or zip file of your
        reproducer here.<br/>
        **NOTE:** PrimeFaces test can easily be set to use the latest `master-SNAPSHOT` of what is in GitHub.
        Please test with that before reporting a bug that may already be fixed.

        Please discibe the steps to take using your reproducer to encounter the issue. For example:

        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

        We encourage you provide a reproducer. If you are unable to, at least provide us with a sample
        XHTML and bean:

        ```xhtml
        <h:form id="frmTest">
        </h:form>
        ```

        ```java
        @Named
        @ViewScoped
        public class TestView implements Serializable {
        }
        ```
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: input
    id: pfe-version
    attributes:
      label: PrimeFaces Extensions version
    validations:
      required: true
  - type: dropdown
    id: jsf-implementation
    attributes:
      label: JSF implementation
      multiple: false
      options:
        - Mojarra
        - MyFaces
  - type: input
    id: jsf-version
    attributes:
      label: JSF version
    validations:
      required: false
  - type: input
    id: browsers
    attributes:
      label: Affected browsers
      description: Is the issue occures in specific browsers (or versions) only, mention them here.
