<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.primefaces.extensions</groupId>
        <artifactId>primefaces-extensions-parent</artifactId>
        <version>17.0.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>primefaces-extensions-integration-tests</artifactId>
    <packaging>war</packaging>

    <name>PrimeFaces Extensions Integration Tests</name>
    <description>
        <![CDATA[PrimeFaces Extensions regression test suite using Selenium.]]>
    </description>

    <properties>
        <webdriver.headless>false</webdriver.headless>
        <webdriver.browser>chrome</webdriver.browser>
        <primefaces.CSP>false</primefaces.CSP>
        <primefaces.THEME>aura-light-emerald</primefaces.THEME>
        <junit.jupiter.execution.parallel.enabled>false</junit.jupiter.execution.parallel.enabled>
        <jakarta.faces.STATE_SAVING_METHOD>server</jakarta.faces.STATE_SAVING_METHOD>

        <tomcat.version>11.0.26</tomcat.version>
        <jetty.version>12.1.13</jetty.version>

        <main.basedir>${project.parent.basedir}</main.basedir>

        <sonar.skip>true</sonar.skip>
    </properties>

    <dependencies>
        <!-- PrimeFaces -->
        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <version>${primefaces.core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces-themes</artifactId>
            <version>${primefaces.core.version}</version>
        </dependency>

        <!-- Jakarta EE API -->
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>11.0.0</version>
            <scope>provided</scope>
        </dependency>

        <!-- JSF implementation -->
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>jakarta.faces</artifactId>
            <version>${jakarta-faces.version}</version>
            <scope>runtime</scope>
        </dependency>

        <!-- CDI / Weld -->
        <dependency>
            <groupId>org.jboss.weld.servlet</groupId>
            <artifactId>weld-servlet-core</artifactId>
            <version>6.0.4.Final</version>
        </dependency>

        <!-- Tomcat embedded -->
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
            <version>${tomcat.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-jasper</artifactId>
            <version>${tomcat.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-el</artifactId>
            <version>${tomcat.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-websocket</artifactId>
            <version>${tomcat.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- BV - Hibernate Validator -->
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>9.1.4.Final</version>
            <scope>runtime</scope>
        </dependency>

        <!-- PFE -->
        <dependency>
            <groupId>org.primefaces.extensions</groupId>
            <artifactId>primefaces-extensions</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- PF Selenium -->
        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces-selenium-core</artifactId>
            <version>${primefaces.core.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces-selenium-components</artifactId>
            <version>${primefaces.core.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.primefaces.extensions</groupId>
            <artifactId>primefaces-extensions-selenium-components</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>primefaces-extensions-integration-tests</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>src/main/webapp/WEB-INF</directory>
                <includes>
                    <include>web.xml</include>
                </includes>
                <filtering>true</filtering>
                <targetPath>${project.build.directory}</targetPath>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
            </testResource>
            <testResource>
                <directory>src/test/resources-filtered</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>
        <plugins>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <webResources>
                        <resource>
                            <filtering>true</filtering>
                            <directory>src/main/webapp</directory>
                            <includes>
                                <include>**/WEB-INF/*.xml</include>
                            </includes>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.6.0</version>
            </plugin>
            <plugin>
                <groupId>org.eclipse.jetty.ee10</groupId>
                <artifactId>jetty-ee10-maven-plugin</artifactId>
                <version>${jetty.version}</version>
                <configuration>
                    <httpConnector>
                        <host>0.0.0.0</host>
                        <port>8080</port>
                    </httpConnector>
                    <webXml>${project.build.directory}/web.xml</webXml>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.eclipse.jetty.ee10</groupId>
                        <artifactId>jetty-ee10-cdi</artifactId>
                        <version>${jetty.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>integration-tests</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <skip>false</skip>
                            <trimStackTrace>false</trimStackTrace>
                            <includes>
                                <include>**/*Test</include>
                            </includes>
                            <systemPropertyVariables>
                                <webdriver.browser>${webdriver.browser}</webdriver.browser>
                                <webdriver.headless>${webdriver.headless}</webdriver.headless>
                                <primefaces.CSP>${primefaces.CSP}</primefaces.CSP>
                                <primefaces.THEME>${primefaces.THEME}</primefaces.THEME>
                                <junit.jupiter.execution.parallel.enabled>${junit.jupiter.execution.parallel.enabled}</junit.jupiter.execution.parallel.enabled>
                                <junit.jupiter.execution.parallel.mode.default>same_thread</junit.jupiter.execution.parallel.mode.default>
                                <junit.jupiter.execution.parallel.mode.classes.default>concurrent</junit.jupiter.execution.parallel.mode.classes.default>
                                <junit.jupiter.execution.parallel.config.strategy>custom</junit.jupiter.execution.parallel.config.strategy>
                                <junit.jupiter.execution.parallel.config.custom.class>org.primefaces.extensions.integrationtests.JUnit5Selenium4Strategy</junit.jupiter.execution.parallel.config.custom.class>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>headless</id>
            <properties>
                <webdriver.headless>true</webdriver.headless>
            </properties>
        </profile>
        <profile>
            <id>chrome</id>
            <properties>
                <webdriver.browser>chrome</webdriver.browser>
            </properties>
        </profile>
        <profile>
            <id>firefox</id>
            <properties>
                <webdriver.browser>firefox</webdriver.browser>
            </properties>
        </profile>
        <profile>
            <id>client-state-saving</id>
            <properties>
                <jakarta.faces.STATE_SAVING_METHOD>client</jakarta.faces.STATE_SAVING_METHOD>
            </properties>
        </profile>
        <profile>
            <id>theme-aura</id>
            <properties>
                <primefaces.THEME>aura-light-emerald</primefaces.THEME>
            </properties>
        </profile>
    </profiles>
</project>
